[package]
name = "portfolio_website"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
mime_guess = "2"
thiserror = "1"
